from datetime import datetime, timedelta, timezone

now = datetime.now(timezone.utc)

news_items: list[dict] = [
    {
        "id": "krx-macro-001",
        "type": "macro",
        "title": "한국은행, 기준금리 동결 기조 재확인",
        "summary": "물가와 성장 둔화 사이 균형을 고려한 동결 기조가 유지됐습니다.",
        "why_it_matters": "은행주와 내수주 상대 강도 변화 가능성이 커졌습니다.",
        "source": "Argus KRX Desk",
        "source_url": "https://example.com/krx-macro-001",
        "published_at": now.isoformat(),
        "sentiment": "neutral",
        "importance": "high",
        "related_sectors": ["금융", "소비재"],
        "related_tickers": ["105560.KS", "035420.KS"],
        "category": "금리",
        "tags": ["한은", "기준금리", "국내증시"],
    },
    {
        "id": "krx-macro-002",
        "type": "macro",
        "title": "원/달러 환율 1,330원대 유지",
        "summary": "달러 강세 영향으로 원화 변동성이 높은 수준을 보였습니다.",
        "why_it_matters": "수입 원가와 외국인 수급에 영향을 줄 수 있습니다.",
        "source": "Argus KRX Desk",
        "source_url": "https://example.com/krx-macro-002",
        "published_at": (now - timedelta(hours=3)).isoformat(),
        "sentiment": "negative",
        "importance": "medium",
        "related_sectors": ["반도체", "산업재"],
        "related_tickers": ["005930.KS", "000660.KS"],
        "category": "환율",
        "tags": ["환율", "원화", "달러"],
    },
    {
        "id": "krx-stock-001",
        "type": "stock",
        "title": "삼성전자, HBM 공급 확대 기대",
        "summary": "고부가 메모리 공급 논의가 구체화되고 있습니다.",
        "why_it_matters": "메모리 수익성 개선과 밸류체인 투자심리에 긍정적입니다.",
        "source": "Argus KRX Desk",
        "source_url": "https://example.com/krx-stock-001",
        "published_at": (now - timedelta(hours=1)).isoformat(),
        "sentiment": "positive",
        "importance": "high",
        "related_sectors": ["반도체"],
        "related_tickers": ["005930.KS", "000660.KS"],
        "category": "수주/계약",
        "tags": ["HBM", "반도체", "공급"],
    },
    {
        "id": "krx-stock-002",
        "type": "stock",
        "title": "NAVER, AI 서비스 고도화 계획 발표",
        "summary": "검색·광고·커머스 영역에 생성형 AI 기능을 확대 적용합니다.",
        "why_it_matters": "서비스 체류시간과 광고 효율 개선이 핵심 포인트입니다.",
        "source": "Argus KRX Desk",
        "source_url": "https://example.com/krx-stock-002",
        "published_at": (now - timedelta(hours=6)).isoformat(),
        "sentiment": "positive",
        "importance": "medium",
        "related_sectors": ["커뮤니케이션", "테크"],
        "related_tickers": ["035420.KS"],
        "category": "제품 출시",
        "tags": ["AI", "플랫폼", "광고"],
    },
]
